version: '2'
services:
  easy_ssb_pub:
    build: .
    environment:
      HOST: "${HOST}"
      DEBUG: "${DEBUG}"
    volumes:
      - $HOME/.ssb:/root/.ssb
    container_name: easy-ssb-pub
    mem_limit: 450M
    restart: unless-stopped

  nginx:
      image: nginx:alpine
      ports:
        - "80:80"
        - "8007:8007"
        - "8008:8008"  
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      restart: unless-stopped
      networks:
        - internal

  networks:
    internal:
      driver: bridge