services:
  easy_ssb_pub:
    build: .
    environment:
      HOST: "${HOST}"
      DEBUG: "${DEBUG}"
    ports:
      - "8008:8008"
    volumes:
      - $HOME/.ssb:/root/.ssb
    container_name: easy-ssb-pub
    mem_limit: 450M
    restart: unless-stopped
    networks:
      - internal

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8007:8007"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge